apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-chingari-chat-helper
  namespace: chingari-chat-helper
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-chingari-chat-helper
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
